spring:
  datasource:
        #MySQL
    #url: jdbc:mysql://endereco/nome_do_bd
    #username: root
    #password: senha
        #PostgreSQL
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none #validate
    properties:
      hibernate:
        format-sql: true
      