spring:
  datasource:
        #MySQL
    #url: jdbc:mysql://endereco/nome_do_bd
    #username: root
    #password: senha
        #PostgreSQL
    url: jdbc:postgresql://localhost:5432/sistema_agendamento_livro_db
    username: postgres
    password: PQFL2024
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none #validate
    properties:
      hibernate:
        format-sql: true
      